server:
  port: ${WEB_PORT:8081}
  servlet:
    context-path: ${WEB_CONTEXT_PATH:/app-web/v1}
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,loggers,info}
  endpoint:
    loggers:
      enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: ${DATASOURCE_MAX_POOL_SIZE:20}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_REALM_CERT_URL:http://localhost:80/realms/load-testing/protocol/openid-connect/certs}

  jackson:
    deserialization:
      fail-on-unknown-properties: true
  application:
    name: app-web

logging:
  level:
    root: debug
